export const ROL_PLANEACION = 'PLANEACION';
export const ROL_JEFE_DEPENDENCIA = 'JEFE_DEPENDENCIA';
export const ROL_ASISTENTE_DEPENDENCIA = 'ASISTENTE_DEPENDENCIA';
export const ROL_ASISTENTE_PLANEACION = 'ASISTENTE_PLANEACION';