export const ROL_PLANEACION = 'PLANEACION';
export const ROL_JEFE_UNIDAD_PLANEACION = 'JEFE_UNIDAD_PLANEACION';
export const ROL_JEFE_DEPENDENCIA = 'JEFE_DEPENDENCIA';
export const ROL_ASISTENTE_DEPENDENCIA = 'ASISTENTE_DEPENDENCIA';